//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "metric")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub metric_id: i64,
    pub kind: String,
    #[sea_orm(unique)]
    pub metric_code: String,
    pub metric_name: String,
    pub unit: Option<String>,
    pub value_type: String,
    pub visualization: String,
    pub status: String,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::observation::Entity")]
    Observation,
    #[sea_orm(has_one = "super::recipe::Entity", has_many = "super::recipe::Entity")]
    Recipe,
}

impl Related<super::observation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Observation.def()
    }
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
