//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "observation")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub observation_id: i64,
    pub subject_id: i64,
    pub recipe_id: i64,
    pub value: String,
    pub observed_at: TimeDateTimeWithTimeZone,
    pub recorded_at: TimeDateTimeWithTimeZone,
    pub source_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recipe::Entity",
        from = "Column::RecipeId",
        to = "super::recipe::Column::RecipeId",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Recipe,
}

impl Related<super::recipe::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Recipe.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
