//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::{
    data_source::Entity as DataSource, metric::Entity as Metric,
    observation::Entity as Observation, recipe::Entity as Recipe, subject::Entity as Subject,
};
