//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub output_metric_id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub deps: Json,
    pub calc_key: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub arg_map: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub expr: Option<Json>,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
