//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "recipe")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub recipe_id: i64,
    pub metric_id: i64,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub deps: Json,
    pub calc_key: String,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub arg_map: Json,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub expr: Json,
    pub created_at: TimeDateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::metric::Entity",
        from = "Column::MetricId",
        to = "super::metric::Column::MetricId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Metric,
}

impl Related<super::metric::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metric.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
