//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "lipid_records")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub user_id: i64,
    pub measure_time: TimeDate,
    pub tg_mmol: Option<Decimal>,
    pub hdl_mmol: Option<Decimal>,
    pub ldl_mmol: Option<Decimal>,
    pub tc_mmol: Option<Decimal>,
    #[sea_orm(column_type = "JsonBinary")]
    pub extra: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub source: Option<String>,
    pub created_at: TimeDateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
