//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub use super::{
    blood_pressure_records::Entity as BloodPressureRecords,
    blood_routine_records::Entity as BloodRoutineRecords, body_records::Entity as BodyRecords,
    lipid_records::Entity as LipidRecords, liver_function_records::Entity as LiverFunctionRecords,
    other_metrics_records::Entity as OtherMetricsRecords, prompt::Entity as Prompt,
    renal_function_records::Entity as RenalFunctionRecords, sleep_records::Entity as SleepRecords,
    urine_records::Entity as UrineRecords, users::Entity as Users,
};
